import test from 'node:test';
import assert from 'node:assert/strict';
import {checkCandidate} from './candidate_check.mjs';
import {makeManifest,plannedOrder,sha256,protocol} from './candidate_manifest.mjs';
function setup(){const m=makeManifest(),rows=plannedOrder().map((cell,i)=>({...cell,task_id:`task-${i}`,provider:'bench-live',model:protocol.model,outcome:'completed',verified:true,broken_first_failed:true,protected_unchanged:true,observed_changes:['subject/src/implementation.rs'],expected_changes:['subject/src/implementation.rs'],observed_matches_expected:true,task_wall_ms:100,completion_ms:100,model_ms:80,first_evidence_ms:1,first_edit_ms:85,evidence_concurrency:2,model_calls:1,retries:0,provider_failures:0,verification_failures:0,input_tokens:17,output_tokens:9,usage_provenance:'provider_reported',recovery:'recovered_completed',model_attempts:[{attempt:1,latency_ms:80,error:null,output_failure:null,usage:{input_tokens:17,output_tokens:9,provenance:'provider_reported'}}]}));return{rows,m,meta:{schema:1,manifest_sha256:sha256(JSON.stringify(m,null,2)+'\n'),source_commit:'1'.repeat(40),binary_sha256:'2'.repeat(64),protocol,planned_order:plannedOrder(),runner_state:{complete:true,in_flight:null,recorded_samples:30}}};}
function fail(r){Object.assign(r,{outcome:'error',verified:false,error:'drive failed: verification_failed',error_code:'verification_failed',failure_durable:true,recovery:'recovered_failed',verification_failures:1});}
const score=s=>checkCandidate(s.rows,s.m,s.meta);
test('tied perfect scores are valid evidence but cannot justify adoption',()=>{const r=score(setup());assert.equal(r.eval_valid,true);assert.equal(r.eligible_for_production_design,false);assert.equal(r.production_adopted,false);assert.equal(r.model_calls,30);assert.equal(r.comparison_allowed,false);});
test('development improvement plus heldout nonregression is eligible only for further design',()=>{const s=setup();fail(s.rows[0]);const r=score(s);assert.equal(r.eligible_for_production_design,true);assert.equal(r.production_adopted,false);});
test('heldout regression or reference-line failure blocks eligibility',()=>{for(const fixture of ['signed-midpoint','duplicate-range']){const s=setup();fail(s.rows[0]);fail(s.rows.find(r=>r.fixture===fixture&&r.proposal_variant==='boundary-guidance'));assert.equal(score(s).eligible_for_production_design,false);}});
test('missing, reordered, mixed, duplicate and unsafe evidence cannot score',()=>{for(const mutate of [s=>s.rows.pop(),s=>s.rows.reverse(),s=>s.rows[0].proposal_variant='unknown',s=>s.rows[0].proposal_variant='boundary-guidance',s=>s.rows[0].task_id=s.rows[1].task_id,s=>s.rows[0].provider='fake',s=>s.rows[0].observed_changes.push('subject/tests/holdout.rs'),s=>s.rows[0].model_ms=121001,s=>s.meta.runner_state.interrupted=true,s=>s.meta.runner_state.in_flight={},s=>s.meta.runner_state.complete=false,s=>s.meta.manifest_sha256='0'.repeat(64),s=>delete s.meta.source_commit,s=>s.m.files[Object.keys(s.m.files)[0]]='0'.repeat(64)]){const s=setup();mutate(s);assert.throws(()=>score(s));}});
