import test from 'node:test';
import assert from 'node:assert/strict';
import {checkBaseline} from './heldout_check.mjs';
import {makeManifest,assertFrozen,plannedOrder,sha256,protocol} from './heldout_manifest.mjs';
function corpus(){return plannedOrder().map((cell,i)=>({...cell,task_id:`task-${i}`,provider:'bench-live',model:protocol.model,outcome:'completed',verified:true,broken_first_failed:true,protected_unchanged:true,observed_changes:['subject/src/implementation.rs'],expected_changes:['subject/src/implementation.rs'],observed_matches_expected:true,task_wall_ms:100,completion_ms:100,model_ms:80,first_evidence_ms:1,first_edit_ms:85,evidence_concurrency:cell.mode==='full'?2:1,model_calls:1,retries:0,provider_failures:0,verification_failures:0,input_tokens:17,output_tokens:9,usage_provenance:'provider_reported',recovery:'recovered_completed',model_attempts:[{attempt:1,latency_ms:80,error:null,output_failure:null,usage:{input_tokens:17,output_tokens:9,provenance:'provider_reported'}}]}));}
function setup(){const manifest=makeManifest();return{rows:corpus(),manifest,meta:{schema:1,manifest_sha256:sha256(JSON.stringify(manifest,null,2)+'\n'),source_commit:'1'.repeat(40),binary_sha256:'2'.repeat(64),protocol,planned_order:plannedOrder(),runner_state:{complete:true,in_flight:null,recorded_samples:30}}};}
test('complete three-task baseline passes while small samples prevent a speed claim',()=>{const{rows,manifest,meta}=setup();const a=checkBaseline(rows,manifest,meta);assert.equal(a.eval_valid,true);assert.equal(a.verified,30);assert.equal(a.model_calls,30);assert.equal(a.reference_line_met,true);assert.equal(a.comparison_allowed,false);});
test('failed product outcomes lower the score without invalidating honest evidence',()=>{const{rows,manifest,meta}=setup();for(const s of rows.slice(0,3)){Object.assign(s,{outcome:'error',verified:false,error:'drive failed: verification_failed',error_code:'verification_failed',failure_durable:true,recovery:'recovered_failed',verification_failures:1});}const a=checkBaseline(rows,manifest,meta);assert.equal(a.eval_valid,true);assert.equal(a.verified,27);assert.equal(a.reference_line_met,false);});
test('missing, reordered, mixed, reused and unsafe rows are rejected',()=>{for(const mutate of [s=>s.rows.pop(),s=>s.rows.reverse(),s=>s.rows[0].fixture='auth-refresh',s=>s.rows[0].sample=2,s=>s.rows[0].model='other',s=>s.rows[0].task_id=s.rows[1].task_id,s=>s.rows[0].observed_changes.push('subject/tests/holdout.rs'),s=>s.rows[0].provider_failures=1,s=>s.rows[0].recovery='recovered_failed']){const s=setup();mutate(s);assert.throws(()=>checkBaseline(s.rows,s.manifest,s.meta));}});
test('source, binary, protocol, manifest and completion provenance cannot be omitted or altered',()=>{for(const mutate of [s=>delete s.meta.source_commit,s=>s.meta.binary_sha256='x',s=>s.meta.manifest_sha256='0'.repeat(64),s=>s.meta.protocol={...protocol,max_attempts:3},s=>s.meta.runner_state.complete=false,s=>s.meta.runner_state.interrupted=true,s=>s.meta.planned_order.reverse(),s=>s.meta.runner_state.in_flight={fixture:'utf8-boundary'},s=>s.meta.runner_state.recorded_samples=29]){const s=setup();mutate(s);assert.throws(()=>checkBaseline(s.rows,s.manifest,s.meta));}});
test('frozen content hashes reject edited, missing and extra inputs',()=>{for(const mutate of [m=>m.files[Object.keys(m.files)[0]]='0'.repeat(64),m=>delete m.files[Object.keys(m.files)[0]],m=>m.files['invented.txt']='0'.repeat(64),m=>m.tasks[0].descriptor_sha256='0'.repeat(64),m=>m.protocol={...protocol,samples_per_cell:4}]){const m=makeManifest();mutate(m);assert.throws(()=>assertFrozen(m));}});

test('real-shaped failed rows need task identity and remain scoreable',()=>{const s=setup(),r=s.rows[0];Object.assign(r,{outcome:'error',verified:false,error:'drive failed: verification_failed',error_code:'verification_failed',failure_durable:true,recovery:'recovered_failed',verification_failures:1});for(const k of ['first_edit_ms','first_evidence_ms','evidence_concurrency','observed_matches_expected'])delete r[k];assert.equal(checkBaseline(s.rows,s.manifest,s.meta).verified,29);delete r.task_id;assert.throws(()=>checkBaseline(s.rows,s.manifest,s.meta),/task reused or absent/);});
test('deadline tolerance is bounded and cannot hide an over-budget call',()=>{const s=setup(),r=s.rows[0];const limit=protocol.model_stage_deadline_ms+protocol.deadline_tolerance_ms;Object.assign(r,{model_ms:limit,task_wall_ms:limit+10,completion_ms:limit+10});r.model_attempts[0].latency_ms=limit;checkBaseline(s.rows,s.manifest,s.meta);r.model_ms++;r.model_attempts[0].latency_ms++;assert.throws(()=>checkBaseline(s.rows,s.manifest,s.meta),/model deadline exceeded/);});
