import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';
import {checkStateful} from './stateful_check.mjs';
import {root,makeManifest,plannedOrder,sha256,protocol} from './stateful_manifest.mjs';
function setup(){const m=makeManifest(),rows=plannedOrder().map((cell,i)=>{const d=JSON.parse(fs.readFileSync(path.join(root,'fixtures',cell.fixture,'bench.json'),'utf8'));return{...cell,task_id:`task-${i}`,proposal_variant:'baseline',provider:'bench-live',model:protocol.model,outcome:'completed',verified:true,broken_first_failed:true,protected_unchanged:true,observed_changes:d.change_paths,expected_changes:d.change_paths,observed_matches_expected:true,task_wall_ms:100,completion_ms:100,model_ms:80,first_evidence_ms:1,first_edit_ms:85,evidence_concurrency:cell.mode==='full'?2:1,model_calls:1,retries:0,provider_failures:0,verification_failures:0,input_tokens:17,output_tokens:9,usage_provenance:'provider_reported',recovery:'recovered_completed',model_attempts:[{attempt:1,latency_ms:80,error:null,output_failure:null,usage:{input_tokens:17,output_tokens:9,provenance:'provider_reported'}}]};});return{rows,m,meta:{schema:1,manifest_sha256:sha256(JSON.stringify(m,null,2)+'\n'),source_commit:'1'.repeat(40),binary_sha256:'2'.repeat(64),protocol,planned_order:plannedOrder(),runner_state:{complete:true,in_flight:null,recorded_samples:20}}};}
const score=s=>checkStateful(s.rows,s.m,s.meta);
test('complete baseline validates all required stateful changes without a speed claim',()=>{const r=score(setup());assert.equal(r.eval_valid,true);assert.equal(r.verified,20);assert.equal(r.model_calls,20);assert.equal(r.reference_line_met,true);assert.equal(r.comparison_allowed,false);});
test('partial patch cannot claim success but honest failed acceptance is valid evidence',()=>{const s=setup();s.rows[0].observed_changes=s.rows[0].observed_changes.slice(0,1);assert.throws(()=>score(s));Object.assign(s.rows[0],{outcome:'error',verified:false,error:'drive failed: verification_failed',error_code:'verification_failed',failure_durable:true,verification_failures:1,recovery:'recovered_failed',observed_matches_expected:false});const r=score(s);assert.equal(r.verified,19);assert.equal(r.eval_valid,true);});
test('failures lower the product reference score without deleting evidence',()=>{const s=setup();for(const r of s.rows.slice(0,2))Object.assign(r,{outcome:'error',verified:false,error:'drive failed: verification_failed',error_code:'verification_failed',failure_durable:true,verification_failures:1,recovery:'recovered_failed'});assert.equal(score(s).verified,18);assert.equal(score(s).reference_line_met,false);});
test('unsafe, incomplete, mixed, unbounded and altered evidence is rejected',()=>{for(const mutate of [s=>s.rows.pop(),s=>s.rows.reverse(),s=>s.rows[0].proposal_variant='boundary-guidance',s=>s.rows[0].model='other',s=>s.rows[0].task_id=s.rows[1].task_id,s=>s.rows[0].observed_changes=['subject/tests/holdout.rs'],s=>s.rows[0].model_ms=121001,s=>s.rows[0].model_calls=2,s=>s.meta.runner_state.complete=false,s=>s.meta.runner_state.interrupted=true,s=>s.meta.runner_state.in_flight={},s=>s.meta.runner_state.recorded_samples=19,s=>delete s.meta.source_commit,s=>s.meta.manifest_sha256='0'.repeat(64),s=>s.m.files[Object.keys(s.m.files)[0]]='0'.repeat(64)]){const s=setup();mutate(s);assert.throws(()=>score(s));}});
test('a three-file catalog repair cannot omit any file and claim completion',()=>{for(let missing=0;missing<3;missing++){const s=setup();const row=s.rows.find(r=>r.fixture==='indexed-catalog');assert.equal(row.expected_changes.length,3);row.observed_changes=row.observed_changes.filter((_,i)=>i!==missing);assert.throws(()=>score(s));}});
